# Generated by Django 3.1.3 on 2020-11-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20201127_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.CharField(max_length=12),
        ),
    ]
