# Generated by Django 3.1.3 on 2020-12-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_itembase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBase',
        ),
    ]
