# Generated by Django 3.1.4 on 2021-03-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_delete_itembase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
